## BÀi 1

In [1]:
import numpy as np

# Lấy phiên bản
print("Phiên bản NumPy hiện tại:", np.__version__)

# Hiển thị cấu hình xây dựng
print("\nCấu hình xây dựng của Numpy:")
print(np.show_config())

Phiên bản NumPy hiện tại: 2.3.4

Cấu hình xây dựng của Numpy:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/L

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


## Bài 2

In [2]:
import numpy as np

# 1. Tạo mảng từ 0-9
arr = np.arange(10)
print("Mảng arr:", arr)
print("Kiểu dữ liệu:", arr.dtype)
print("Kích thước:", arr.shape)

# 2. Tạo arr_odd và arr_even
arr_odd = arr[arr % 2 != 0]
arr_even = arr[arr % 2 == 0]
print("Mảng lẻ:", arr_odd)
print("Mảng chẵn:", arr_even)

# 3. Thay phần tử lẻ bằng 100
arr_update_1 = arr.copy()
arr_update_1[arr_update_1 % 2 != 0] = 100
print("Mảng sau khi update:", arr_update_1)

Mảng arr: [0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu: int64
Kích thước: (10,)
Mảng lẻ: [1 3 5 7 9]
Mảng chẵn: [0 2 4 6 8]
Mảng sau khi update: [  0 100   2 100   4 100   6 100   8 100]


## BÀi 3

In [3]:
import numpy as np

arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

# 1. Phần tử xuất hiện ở cả arr_a và arr_b (Giao nhau)
arr_c = np.intersect1d(arr_a, arr_b)
print("Phần tử chung:", arr_c)

# 2. Phần tử chỉ xuất hiện ở arr_a (Hiệu của 2 mảng)
arr_d = np.setdiff1d(arr_a, arr_b)
print("Chỉ có ở arr_a:", arr_d)

# 3. Lọc phần tử từ 5 đến 10
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("Phần tử từ 5 đến 10:", arr_f)

Phần tử chung: [2 4]
Chỉ có ở arr_a: [1 3 5 6]
Phần tử từ 5 đến 10: [ 6  9 10  8  6]


## BÀi 4

In [4]:
import numpy as np

# 1. Tạo arr_zeros và cập nhật vị trí thứ 5 (index 4) là 1
arr_zeros = np.zeros(10)
arr_zeros[4] = 1 # Vị trí thứ 5 có index là 4
print("arr_zeros:", arr_zeros)

# 2. Tạo arr_h (10-24) và đảo ngược
arr_h = np.arange(10, 25)
print("Mảng đảo ngược:", arr_h[::-1])

# 3. Loại bỏ các số 0
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
print("arr_l (không có số 0):", arr_l)

# 4. Thêm 10 và 20 vào cuối
arr_l = np.append(arr_l, [10, 20])
print("Sau khi thêm 10, 20:", arr_l)

# 5. Thêm 100 vào index 5
arr_l = np.insert(arr_l, 5, 100)
print("Sau khi chèn 100 vào index 5:", arr_l)

# 6. Xóa các phần tử tại index 0, 1, 2
arr_l = np.delete(arr_l, [0, 1, 2])
print("Sau khi xóa index 0, 1, 2:", arr_l)

arr_zeros: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Mảng đảo ngược: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
arr_l (không có số 0): [1 2 8 2 1 3 5]
Sau khi thêm 10, 20: [ 1  2  8  2  1  3  5 10 20]
Sau khi chèn 100 vào index 5: [  1   2   8   2   1 100   3   5  10  20]
Sau khi xóa index 0, 1, 2: [  2   1 100   3   5  10  20]


## Bài 5

In [ ]:
import numpy as np
height = [74, 74, 72, 72, 73, 69, 71, 76, 71, 73] * 10  
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180] * 10
positions = np.array(['GK', 'M', 'A', 'D', 'M'] * 20)

arr_height = np.array(height)
arr_weight = np.array(weight)

arr_height = np.array(height)
arr_weight = np.array(weight)

arr_height_m = arr_height * 0.0254

arr_weight_kg = arr_weight * 0.453592

arr_bmi = arr_weight_kg / (arr_height_m ** 2)

if len(arr_weight_kg) > 50:
    print(arr_weight_kg[50])

arr_height_m_100 = arr_height_m[100:111]

print(arr_bmi[arr_bmi < 21])

print(np.mean(arr_height_m))
print(np.mean(arr_weight_kg))

print(np.max(arr_height_m))
print(np.max(arr_weight_kg))

print(np.min(arr_height_m))
print(np.min(arr_weight_kg))

81.64656
[]
1.8415000000000001
90.6730408
1.9304
104.779752
1.7526
79.83219199999999


## bài 6

In [13]:
# 1. Tạo mảng 3x3 toàn giá trị True
arr_bool = np.full((3, 3), True)

# 2. Tạo arr_1D từ 0-8 và chuyển thành arr_2D (3x3), sau đó đổi cột 1 và cột 3
arr_1D = np.arange(9)
arr_2D = arr_1D.reshape(3, 3)
# Đổi cột (index 0 và 2)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]

# 3. Hoán đổi dòng 1 và dòng 2 (index 0 và 1)
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]

# 4. Đảo ngược các dòng của arr_2D
arr_2D_rev_rows = arr_2D[::-1, :]

# 5. Đảo ngược các cột của arr_2D
arr_2D_rev_cols = arr_2D[:, ::-1]

# 6. Kiểm tra giá trị rỗng trong mảng
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_null = np.isnan(arr_2D_null).any()
print(has_null)

# 7. Thay thế giá trị rỗng bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print(arr_2D_null)


True
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]


## Bài 7

In [ ]:
import numpy as np

# Giả lập dữ liệu baseball
# Cột 0: Chiều cao (inch), Cột 1: Cân nặng (pound)
baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188]] 

# 1.
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)

# 2. 
if len(np_baseball) >= 50:
    print(np_baseball[49, :])
else:
    print(np_baseball[-1, :])

# 3.
np_weight = np_baseball[:, 1]

# 4.
if len(np_baseball) >= 124:
    print(np_baseball[123, 0])

# 5.
print(np.mean(np_baseball, axis=0))

# 6.
correlation = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print(correlation[0, 1])

<class 'numpy.ndarray'>
(5, 2)
[ 73 188]
[ 73.  200.6]
-0.40193133824286936


## BÀi 8

In [ ]:
import numpy as np

df_temp = pd.DataFrame(data)
df_temp.to_csv('euro2012.csv', index=False)
height = [74, 74, 72, 72, 73, 69, 71, 76, 71, 73] * 10  # Tạo 100 phần tử
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180] * 10
positions = np.array(['GK', 'M', 'A', 'D', 'M'] * 20)

arr_height = np.array(height)
arr_weight = np.array(weight)

# 1. Tính chiều cao trung bình của các GK (Goalkeeper)
gk_heights = arr_height[positions == 'GK']
avg_gk_height = np.mean(gk_heights)
print(f"Chiều cao trung bình của GK: {avg_gk_height}")

# 2. Tính chiều cao trung bình của các vị trí khác (không phải GK)
other_heights = arr_height[positions != 'GK']
avg_other_height = np.mean(other_heights)
print(f"Chiều cao trung bình của các vị trí khác: {avg_other_height}")

# 3. Tạo mảng dữ liệu có cấu trúc (Structured Array)
players = np.zeros(len(arr_height), dtype={'names':('position', 'height'), 'formats':('U5', 'f4')})
players['position'] = positions
players['height'] = arr_height

# 4. Sắp xếp mảng players theo height và cho biết vị trí cao nhất/thấp nhất
players_sorted = np.sort(players, order='height')
print(f"Vị trí có chiều cao thấp nhất: {players_sorted[0]}")
print(f"Vị trí có chiều cao cao nhất: {players_sorted[-1]}")

Chiều cao trung bình của GK: 71.5
Chiều cao trung bình của các vị trí khác: 72.75
Vị trí có chiều cao thấp nhất: ('GK', 69.0)
Vị trí có chiều cao cao nhất: ('A', 76.0)


## Bài 9

In [25]:
import pandas as pd
data = {
    'Team': ['Italy', 'Spain', 'Germany', 'England', 'Russia', 'Greece', 'Portugal', 'Denmark'],
    'Goals': [6, 12, 10, 5, 5, 3, 6, 4],
    'Shots on target': [20, 42, 32, 11, 9, 7, 20, 8],
    'Shooting Accuracy': ['50.0%', '55.9%', '53.0%', '40.0%', '35.0%', '30.0%', '45.0%', '42.0%'],
    'Yellow Cards': [16, 11, 4, 5, 6, 9, 12, 4],
    'Red Cards': [0, 0, 0, 0, 1, 1, 0, 0],
    'Subs on': [18, 17, 15, 14, 13, 12, 11, 10],
    'Post-Group players': [20, 23, 23, 23, 23, 23, 23, 23]
}
# BÀI 3.9: Lọc đội ghi trên 6 bàn
print(euro12[euro12['Goals'] > 6])
# 1. Đọc file euro2012.csv và tạo DataFrame euro12
euro12 = pd.read_csv('euro2012.csv')

# 2. In giá trị cột Goals
print(euro12['Goals'])

# 3. Có bao nhiêu đội tham gia Euro2012?
num_teams = euro12.shape[0]
print(f"Số đội tham gia: {num_teams}")

# 4. Thông tin của Euro2012
print(euro12.info())

# 5. Tạo DataFrame mới 'discipline' chỉ chứa 3 cột: 'Team', 'Yellow Cards', 'Red Cards'
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]

# 6. Sắp xếp discipline giảm dần theo Red Cards, sau đó đến Yellow Cards
discipline_sorted = discipline.sort_values(['Red Cards', 'Yellow Cards'], ascending=False)

# 7. Tính trung bình Yellow Cards
avg_yellow = discipline['Yellow Cards'].mean()
print(f"Trung bình thẻ vàng: {avg_yellow}")

# 8. Lọc các đội ghi hơn 6 bàn thắng
goals_over_6 = euro12[euro12['Goals'] > 6]

# 9. In các đội có tên bắt đầu bằng chữ 'G'
teams_G = euro12[euro12['Team'].str.startswith('G')]

# 10. In 7 cột đầu của euro12
print(euro12.iloc[:, :7])

# 11. In tất cả các cột trừ 3 cột cuối
print(euro12.iloc[:, :-3])

# 12. Hiển thị các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards từ England, Italy, Russia
selected_data = euro12.loc[euro12['Team'].isin(['England', 'Italy', 'Russia']), 
                           ['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']]
print(selected_data)

       Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
5   Germany     10               32                32             47.8%   
13    Spain     12               42                33             55.9%   

   % Goals-to-shots  Total shots (inc. Blocked)  Hit Woodwork  Penalty goals  \
5             15.6%                          80             2              1   
13            16.0%                         100             0              1   

    Penalties not scored  ...  Saves made  Saves-to-shots ratio  Fouls Won  \
5                      0  ...          10                 62.6%         63   
13                     0  ...          15                 93.8%        102   

   Fouls Conceded  Offsides  Yellow Cards  Red Cards  Subs on  Subs off  \
5              49        12             4          0       15        15   
13             83        19            11          0       17        17   

    Players Used  
5             17  
13            18  

[2 rows x 35 c

## Bài 10

In [27]:
import pandas as pd
import numpy as np

#BƯỚC 1: TỰ TẠO DỮ LIỆU MẪU ĐỂ CHẠY 
data = {
    'country': ['Vietnam', 'Thailand', 'France', 'Germany', 'USA', 'Canada', 'Nigeria', 'South Africa'],
    'beer_servings': [163, 99, 127, 346, 249, 240, 31, 225],
    'spirit_servings': [70, 200, 151, 117, 158, 122, 2, 76],
    'wine_servings': [1, 1, 370, 175, 84, 100, 2, 81],
    'total_litres_of_pure_alcohol': [4.0, 6.4, 11.8, 11.3, 8.7, 8.2, 9.1, 8.2],
    'continent': ['AS', 'AS', 'EU', 'EU', 'NA', 'NA', 'AF', 'AF']
}
df_sample = pd.DataFrame(data)
df_sample.to_csv('drinks.csv', index=False)

#THỰC HIỆN CÁC YÊU CẦU BÀI 3.10 ---

# 1. Đọc dữ liệu, đặt cột đầu tiên (index_col=0) làm chỉ số
# Lưu ý: Vì file vừa tạo có cột đầu là 'country', nó sẽ thành index
drinks = pd.read_csv('drinks.csv', index_col=0)

# 2. Xem kiểu dữ liệu, kích thước, tên các cột
print("--- 2. Thông tin chung ---")
print(drinks.dtypes)
print(drinks.shape)
print(drinks.columns)

# 3. Xem 5 dòng đầu và cuối
print("\n--- 3. 5 dòng đầu ---")
print(drinks.head(5))
print("\n--- 3. 5 dòng cuối ---")
print(drinks.tail(5))

# 4. Số lượng bia tiêu thụ trung bình ở mỗi châu lục
print("\n--- 4. Bia TB mỗi châu lục ---")
print(drinks.groupby('continent')['beer_servings'].mean())

# 5. Thông tin thống kê về lượng rượu (wine_servings) ở mỗi châu lục
print("\n--- 5. Thống kê Wine mỗi châu lục ---")
print(drinks.groupby('continent')['wine_servings'].describe())

# 6. Mức tiêu thụ đồ uống trung bình mỗi châu lục (tất cả cột số)
print("\n--- 6. TB đồ uống theo châu lục ---")
print(drinks.groupby('continent').mean(numeric_only=True))

# 7. Mức tiêu thụ đồ uống trung vị (median) mỗi châu lục
print("\n--- 7. Trung vị theo châu lục ---")
print(drinks.groupby('continent').median(numeric_only=True))

# 8. Tiêu thụ rượu (spirit) Max, Min, Mean mỗi châu lục
print("\n--- 8. Thống kê Spirit (Max, Min, Mean) ---")
print(drinks.groupby('continent')['spirit_servings'].agg(['max', 'min', 'mean']))

--- 2. Thông tin chung ---
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object
(8, 5)
Index(['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

--- 3. 5 dòng đầu ---
          beer_servings  spirit_servings  wine_servings  \
country                                                   
Vietnam             163               70              1   
Thailand             99              200              1   
France              127              151            370   
Germany             346              117            175   
USA                 249              158             84   

          total_litres_of_pure_alcohol continent  
country                                           
Vietnam                            4.0        AS  
Thailand                   

## Bài 11

In [1]:
import pandas as pd
import numpy as np

stocks1 = pd.DataFrame({
    "date":["2024-01-01","2024-01-02","2024-01-03"],
    "symbol":["AAA","AAA","AAA"],
    "open":[10,11,12],
    "high":[12,np.nan,13],
    "low":[9,10,np.nan],
    "close":[11,10,13],
    "volume":[1000,1100,1200]
})

stocks1["high"] = stocks1["high"].fillna(stocks1.groupby("symbol")["high"].transform("max"))
stocks1["low"] = stocks1["low"].fillna(stocks1.groupby("symbol")["low"].transform("min"))

stocks1["parsed_time"] = pd.to_datetime(stocks1["date"])
stocks1["result"] = np.where(stocks1["close"] > stocks1["open"], "up", "down")

print(stocks1)


         date symbol  open  high   low  close  volume parsed_time result
0  2024-01-01    AAA    10  12.0   9.0     11    1000  2024-01-01     up
1  2024-01-02    AAA    11  13.0  10.0     10    1100  2024-01-02   down
2  2024-01-03    AAA    12  13.0   9.0     13    1200  2024-01-03     up


## Bài 12

In [2]:
import pandas as pd

movies = pd.DataFrame({
    "movieId":[1,2,3],
    "title":["Toy Story","Jumanji","Heat"]
})

ratings = pd.DataFrame({
    "movieId":[1,1,2,3],
    "rating":[4.0,4.5,3.5,5.0],
    "timestamp":[964982703,964982224,964981247,964982400]
})

ratings["parsed_time"] = pd.to_datetime(ratings["timestamp"], unit="s")

rm = ratings.merge(movies, on="movieId")
print(rm.groupby("title")["rating"].mean())

title
Heat         5.00
Jumanji      3.50
Toy Story    4.25
Name: rating, dtype: float64
